### ISSUE TITLE
Electron-Cash-SLP-3.5.1-portable.exe downloaded from official website sha256 checksum doesn't match.

### ISSUE THREAD

**Issue by uauac** [simpleledger/Electron-Cash-SLP#100]
The Electron-Cash-SLP-3.5.1-portable.exe I downloaded from the official website doesn't match the sha256 here: 
https://github.com/Electron-Cash/keys-n-hashes/blob/master/sigs-and-sums/3.5.1/win-linux/JSC.SHA256.Electron-Cash-SLP-3.5.1-portable.exe.txt

The sha256 of the file I downloaded is 9E14C523A5D9D8AB13488E65985D80867BC4AF181426FDD6FA1A602EEC299B4D

The download URL: https://simpleledger.cash/download/685/

**Comment by jcramer** [comment]
I just double checked and I think you made a mistake,  I still get `d77fc7715c8d55cf42b0492a1a481feb1bce6643aaf9fb779274f4272f13069c`.  

Please try again with:

`$ sha256sum ./Electron-Cash-SLP-3.5.1-portable.exe`

**Comment by uauac** [comment]
It's fine now. That downloaded file can't be opened. Should be my network problem.
