### ISSUE TITLE
Investigate network testing 

### ISSUE THREAD

**Issue by blockparty-sh** [simpleledger/Electron-Cash-SLP#105]
It would be useful to gain a better understanding of Electron Cash's performance with poor networking so that it may better serve users who do not have access to normal internet connections. 

It would be helpful to run tests with artificially high packet loss and low bandwidth:

https://stackoverflow.com/questions/614795/simulate-delayed-and-dropped-packets-on-linux

**Comment by jcramer** [comment]
Closing this as we completed this testing.
