### ISSUE TITLE
For multisig wallets, Master Pub Keys don't toggle with radio buttons

### ISSUE THREAD

**Issue by jcramer** [simpleledger/Electron-Cash-SLP#118]
A user reported these radio buttons are broken in EC SLP, must use EC mainline to get this information:

<img width="125" alt="image" src="https://user-images.githubusercontent.com/988195/74048874-0921e500-49a1-11ea-806b-9ed20cf43614.png">

**Comment by cculianu** [comment]
Hi -- I just tried this on both EC-SLP master and Electron Cash regular master and both seem to work as intended.  I used a multisig 2 or 2.  I can try a 2 of 3 as well... It seems the UI element is working.  Let me know how to reproduce...

**Comment by cculianu** [comment]
Can confirm the code is the same in both EC Regular and EC-SLP for this window.

**Comment by cculianu** [comment]
This may be related to Qt 5.11 bugs on Mojave...

**Comment by jcramer** [comment]
Correct, as we discussed this issue is being caused in macOS due to the known Qt 5.11 bugs with newer macOS versions.  Subsequent builds for macOS need to use a different version of Qt.
