### ISSUE TITLE
nit: Would be nice to have more than 20 chars for token description

### ISSUE THREAD

**Issue by emergent-reasons** [simpleledger/Electron-Cash-SLP#119]
I looked at my token list and realized there are some very valuable ones mixed in with complete random stuff. So I tried documenting them a bit with the description field. Turns out 20 is limiting even for a concise context that also includes the ticker.

If it doesn't cause other problems, it would be nice to have more space.

**Comment by cculianu** [comment]
Weird that the limit would be so small.  It's 100% UI thing since the protocol itself doesn't use any description fields.. (just document URL).

I'm doing SLP integration into EC regular now -- I'll be sure to allow for longer description fields here.

**Comment by jcramer** [comment]
This is fixed.
