### ISSUE TITLE
Client side timeout when downloading large graph search

### ISSUE THREAD

**Issue by blockparty-sh** [simpleledger/Electron-Cash-SLP#123]
Kieran: From the looks of it Electron Cash SLP drops the connection when it gets about 70ish MB of data and seems to restart the query

`ea6ce7a42317c287216ef4437718052e13483e8389d15796a9c8fffe01b5b9e1`

`7a83c576ca3ef09abc5d3ebe6076dfd8ef7f136d3202943d040138c888c78e79`

**Comment by mesquka** [comment]
Runtime Log:
https://gist.github.com/mesquka/3c16b8b52093893273e7ddc28fac60fe

`f80a41d74f13067146090db39129898bad6f1bd2fb9fc200291d9ab41024455f` is another TXID with this issue

**Comment by jcramer** [comment]
This issue is fixed in the above commit.
