### ISSUE TITLE
trezor lib version in requirements-hw.txt

### ISSUE THREAD

**Issue by molecular** [simpleledger/Electron-Cash-SLP#124]
I installed requirements using `pip install -r contrib/requirements/requirements-hw.txt`, but this install incompatible trezor version 0.12

This diff fixed it

```
--- a/contrib/requirements/requirements-hw.txt
+++ b/contrib/requirements/requirements-hw.txt
@@ -1,4 +1,4 @@
-trezor[hidapi]>=0.11.0
+trezor[hidapi]>=0.11.0,<0.12
```

Not sure this applies to other electron-cash versions, just leaving this here because that's where it popped up for me.

**Comment by jcramer** [comment]
@cculianu is this the only place this would need to be updated?

**Comment by molecular** [comment]
@jcramer in deterministic requirements files exact versions are given. example:

```
trezor==0.11.2 \
    --hash=sha256:7bdec3d6e35e41666580547674f2652c0c466172964da42b325cab2c30b4eb46 \
    --hash=sha256:a6f4b47b37a21247535fc43411cb70a8c61ef0a5a2dfee668bd05611e2741fb8
```

**Comment by jcramer** [comment]
Sorry, I misread the original issue.  I reverted the deterministic portion, and I believe this issue is resolved.

**Comment by molecular** [comment]
why did you put version 12 into the deterministic requirements? Unless something changed since I made the issue it's not compatible imo.
