### ISSUE TITLE
Trezor and Ledger has error on signing OP_RETURN txns

### ISSUE THREAD

**Issue by jcramer** [simpleledger/Electron-Cash-SLP#13]
Users are unable to perform both SEND and MINT txns when using Ledger nano.

Also Trezor should be tested

**Comment by jcramer** [comment]
Trezor output:

<img width="410" alt="image" src="https://user-images.githubusercontent.com/988195/44607453-79917200-a7be-11e8-84e0-048419e303fd.png">

**Comment by cculianu** [comment]
Anyone got one of these devices?  I don't have one.  I do have the emulator though.. Hmm.

**Comment by jcramer** [comment]
@cculianu I'm trying to debug this issue with a Trezor on macOS.  However, when I run from source I am not able to connect to Trezor.  Is there something special about the built and packaged that allows use of Trezor.  It works fine with your build for masOS.

Anyways the issue could be related to use of simpleledger address format... but haven't been able to test though.

Here is the error I receive when trying to connect running the source:

<img width="540" alt="image" src="https://user-images.githubusercontent.com/988195/44782346-ec9b3f80-ab54-11e8-82b5-144fe90c67df.png">

**Comment by cculianu** [comment]
I know there are python packages that the trezor stuff depends on.  Maybe you need to make sure they are installed locally into your python install by using pip3?

Have a look in contrib/requirements/requirements-hw.txt and contrib/deterministic-build/requirements-hw.txt and make sure all those packages are installed?

I have no idea otherwise.  It's good to know my build works though! Ha!

**Comment by jcramer** [comment]
Some old dialog on this topic:
https://github.com/trezor/trezor-mcu/issues/456#issuecomment-469704511

I am closing this issue since hardware wallets are not supported in SLP wallets types.

**Comment by nyusternie** [comment]
> hardware wallets are not supported in SLP wallets types

I'd like to start using my Ledger S to store SLP tokens. Is this currently available with EC SLP? If not, can you recommend the "most" secure method for securing SLP tokens.

Thanks!
