### ISSUE TITLE
SLP invalid w/ history of burned tokens

### ISSUE THREAD

**Issue by spice-trader-44148** [simpleledger/Electron-Cash-SLP#130]
I burned some tokens, then used the dust for another token transaction. Rebuilt history for reasons, but only added the non burned tokens.After validation was done, I had a few tokens showing as invalid. I rebuilt again this time adding the tokens i burned to my token list and everything validated fine.

**Comment by jcramer** [comment]
Closing this, as sometimes this happens with the current validator built-in.  In the future, we can replace it with something else more scalable.
