### ISSUE TITLE
Impossible to read token amount / bch amount fields in dark theme due to dark Blue coloured numbers used :-(

### ISSUE THREAD

**Issue by ElDoradoTG** [simpleledger/Electron-Cash-SLP#137]
Version 3.6.5.

Use-case: 
1 - Select DARK theme
2 - Go to SEND tab
3 - Select a TOKEN TYPE or BCH AMOUNT 
4 - Select MAX button or write amount of tokens to be send in field TOKEN AMOUNT or select BCH Amount and enter some BCH sats.

Token amount / BCH amount fields cannot be read due to the very dark blue colored numbers used instead of White colored characters :-(
When theme is reset to standard theme, the dark blue numbers stay in both fields. 

I regret very much I updated to the latest version. Please fix this bug a.s.a.p. 

Advice> Use White colored number and characters at all times.

**Comment by jcramer** [comment]
@cculianu this is the same on mainline EC.  On OS other than macOS, the dark mode the text is too hard to read in the amount fields and fee fields of the send tab.  Please advise :)

**Comment by ElDoradoTG** [comment]
@jcramer Hi James, thanks for fixing the issue, much apreciated, When can we expect the EC SLP version update to be available please?

**Comment by jcramer** [comment]
I'm working on a new experimental feature, so maybe will have a dev version with this incorporated very soon, next day or so...

**Comment by ElDoradoTG** [comment]
> 
> 
> I'm working on a new experimental feature, so maybe will have a dev version with this incorporated very soon, next day or so...

Looking forward to a new version. Thanks a lot in advance,

**Comment by ElDoradoTG** [comment]
I did some comparisons between the previous and latest version, My findings are like that the latest EC SLP version is noticable slower in acting to user command / showing responses and takes longer to load. 

Maybe this can be taken into account as well for the new version? Maybe some code optimization can be executed?

Thanks a lot in advance.

**Comment by ElDoradoTG** [comment]
Where can I obtain the new test version please?
