### ISSUE TITLE
ECSLP not aware of SLP balance

### ISSUE THREAD

**Issue by sonofliberty** [simpleledger/Electron-Cash-SLP#143]
```
user@83ba07cb161f:~/.electron-cash$ electron-cash ismine simpleledger:qrty48flytepfcv6k7hg9gt7eerf9u3sv5dh6llkks
true

user@83ba07cb161f:~/.electron-cash$ electron-cash getbalance_slp 9fc89d6b7d5be2eac0b3787c5b8236bca5de641b5bafafc8f450727b63615c11
{
    "valid": "0"
}
```

At the time I had 0.499 USDt.

I found this in my wallet file:
```
"tx_tokinfo": {
        "e90ee5d87ea84ee3989f2911bf6e3684ae7753e3664143a85c3d369aaca4bc20": {
            "token_id": "9fc89d6b7d5be2eac0b3787c5b8236bca5de641b5bafafc8f450727b63615c11",
            "transaction_type": "SEND",
            "type": "SLP1",
            "validity": 0
        }
    },
```

This problem occurs with version 3.6.4 and 3.6.5.

**Comment by sonofliberty** [comment]
I need to add that it works perfectly when running the GUI.

**Comment by jcramer** [comment]
I think I need some more information:
1) What wallet file are you trying to load from via CLI, is it "default_wallet"?  If it's not "default_wallet" then I think you need to specify the wallet file using the `-w` flag.
2) Do you have graph search enabled in `~/.electron-cash/config`?  You need `"slp_validator_graphsearch_enabled": true` and `"slp_gs_host": "https://gs.ny1.simpleledger.io"` (or `https://gs.fountainhead.cash`)
3) Are you on the same machine looking at the GUI and the daemon?

**Comment by jcramer** [comment]
Also, make sure you run `electron-cash daemon` in the background first, otherwise the wallet won't be running validation.  Note, SLP Edition won't work with `electron-cash daemon start`, so don't use it that way.

**Comment by jcramer** [comment]
Here's the workflow for using `getbalance_slp` on a headless machine:

1) run `$ somepath/electron-cash daemon` as a background process
2) run `$ somepath/electron-cash daemon load_wallet -w <wallet_path`
3) run `$ somepath/electron-cash getbalance_slp <tokenId> -w <wallet_path>`

Using -w isn't required if you're using default_wallet file.

**Comment by sonofliberty** [comment]
> Also, make sure you run `electron-cash daemon` in the background first, otherwise the wallet won't be running validation. Note, SLP Edition won't work with `electron-cash daemon start`, so don't use it that way.

**That's it!** Changing `electron-cash daemon start` to `electron-cash daemon` fixed my problem. Thank you!
