### ISSUE TITLE
Minting transactions cause graph search to break

### ISSUE THREAD

**Issue by ElDoradoTG** [simpleledger/Electron-Cash-SLP#144]
For the last 5 days the Electron Cash SLP version wallets do not display updated token balances under the TOKENS tab. Switching servers in Tools > Network > "Server" or "Tokens" tabs do not make any difference. Wallet hangs (locks up) when selected. 

In case wallet comes back to active status, after like 20 or more minutes waiting, the token balance in tab TOKENS is displayed, but not updated. Log shows that no data can be obtained. The HISTORY and SLP History tabs are updated.

Seen on at least 6 wallets, all version 3.6.5 on various different internet connections / IP addresses.

**Comment by jcramer** [comment]
Please test this pre-release to see if the issue is resolved:

https://github.com/simpleledger/Electron-Cash-SLP/releases/tag/3.6.5-dev2

Some significant performance improvements were made in commit: https://github.com/simpleledger/Electron-Cash-SLP/commit/b5c6a96427c974863bd56c162b8252836ad1d5a2

**Comment by ElDoradoTG** [comment]
Thanks, I will test!

**Comment by ElDoradoTG** [comment]
Hi jcramer,  Both the portable version as well the installation.exe produced : "Failed to execute script electron.cash." on two laptops. What to do next?

**Comment by jcramer** [comment]
Ok, let me fix/ rebuild.

**Comment by jcramer** [comment]
https://github.com/simpleledger/Electron-Cash-SLP/releases/tag/3.6.6-RC2

**Comment by ElDoradoTG** [comment]
Let me try the new build, thanks for the quick actions taken.

**Comment by ElDoradoTG** [comment]
Installed the RC2 version. The good news: The wallet is restored. The less good news: Rebuild of history was needed twice and furthermore restart of failed downloads which took over 1 Hour. 

Wallet is still very slow when switching between the tabs (e.g. TOKENS and SLP HISTORY). Takes 3-5 minutes before wallets even responds.

These wallets have multiple 1000 transactions, as they are used for mining of tokens. But also my default wallet where only tokens are stored and occasionally a BCH payment, suffers from the exact same slowness.

I noticed that the CPU usage is quite low (using a XEON processor like 13-15% maximum)?

**Comment by jcramer** [comment]
Please send me a telegram message with your wallet's xpub and I can try to debug further and compare performance.

**Comment by jcramer** [comment]
At least part of the problem is that the graph search server breaks down on mint transactions for some reason.

**Comment by jcramer** [comment]
Please try this one:

https://github.com/simpleledger/Electron-Cash-SLP/releases/tag/3.6.6-RC3

**Comment by jcramer** [comment]
This is fixed when using BCHD based graph search servers.
