### ISSUE TITLE
3.6.6 does not run on my Mac

### ISSUE THREAD

**Issue by Beakerboy** [simpleledger/Electron-Cash-SLP#181]
I downloaded Electron-Cash-SLP-3.6.6-macosx.dmg from Simpleledger.cash.
I'm running High Sierra 10.13.6 on a MacBook Pro 2.9 GHz Intel Core i7 with 8 GB 1600 MHz DDR3 memory.
I drag and drop the icon to the application directory and it seems to install. When I run the application it warns me that it is a file downloaded from the internet, and I select open. Then nothing happens. No dialog box pops up. If I reboot and try running the application, still nothing.

I have not tried any earlier versions.

Let me know if there are any particular log files that I should paste here to help diagnose the issue.

**Comment by jcramer** [comment]
High Sierra isn't supported anymore, as it requires building the application using High Sierra.  Due to the overhead required we decided to stop supporting it.

Closing this, hope this helps.

**Comment by Beakerboy** [comment]
Thank you for the quick reply. Is this mentioned anywhere in the documentation? The readme says it is compiled on El Capitan, and with High Sierra coming out after El Capitan, I assumed it should work. Is there something wrong with my assumption, or is there something that need to be clarified in the requirements.

**Comment by jcramer** [comment]
The readme needs to be updated.  You can build it on High Sierra, or just run it from source.
