### ISSUE TITLE
Update contrib/osx/README.md

### ISSUE THREAD

**Issue by Beakerboy** [simpleledger/Electron-Cash-SLP#182]
#181 mentions that the Readme for OSX is out of date, but since that issue has been closed, I thought it best to have an open issue to resolve the confusion.

It might be a good idea to review the entire readme, and maybe the rest of the readme files to ensure accuracy. I would like to build this from source on Mac High Sierra, but I want to make sure the directions are correct.

**Comment by jcramer** [comment]
See if this helps:  https://github.com/Electron-Cash/Electron-Cash/blob/master/contrib/osx/README.md

We should port over the latest readme to match.

**Comment by Beakerboy** [comment]
I saw that, thanks for verifying that it is still accurate.

**Comment by jcramer** [comment]
Closing this since, the instructions are still accurate as far as I'm aware.  If you find otherwise in your investigation please open another issue with corrections of the current readme.

**Comment by Beakerboy** [comment]
The readme says

> We build our binaries on El Capitan (10.11.6) as building it on High Sierra makes the binaries incompatible with older versions.

but that is not true. It is built on Mojave or something newer. High Sierra will not run the binary.

**Comment by jcramer** [comment]
@cculianu I thih

**Comment by jcramer** [comment]
There readme is fixed.
