### ISSUE TITLE
Building on OSX High Sierra. Zbar does not build.

### ISSUE THREAD

**Issue by Beakerboy** [simpleledger/Electron-Cash-SLP#187]
Any hints on what to look at after receiving this error?

> 💬 INFO:  Building zbar...
> ~/development/git/Electron-Cash-SLP/contrib/zbar ~/development/git/Electron-Cash-SLP
> make: *** No targets specified and no makefile found.  Stop.
> 🗯  ERROR:  Could not build zbar
> 🗯  ERROR:  Could not build ZBar

**Comment by EchterAgo** [comment]
Maybe submodules are not up to date? What does `ls -lah contrib/zbar` show?

**Comment by Beakerboy** [comment]
`ls -lah contrib/zbar` shows a long list of files, dated today. 

```
kevin$ ls -lah contrib/zbar
total 3968
drwxr-xr-x  51 kevin  staff   1.7K Mar 20 09:59 .
drwxr-xr-x  35 kevin  staff   1.2K Mar 20 07:37 ..
-rw-r--r--   1 kevin  staff    40B Mar 20 08:22 .git
drwxr-xr-x   3 kevin  staff   102B Mar 20 08:23 .github
-rw-r--r--   1 kevin  staff   1.1K Mar 20 08:23 .gitignore
-rw-r--r--   1 kevin  staff   461B Mar 20 08:23 .hgignore
-rw-r--r--   1 kevin  staff   1.5K Mar 20 08:23 .hgtags
-rw-r--r--   1 kevin  staff    67B Mar 20 09:46 ABOUT-NLS
-rw-r--r--   1 kevin  staff   1.2K Mar 20 08:23 COPYING
-rw-r--r--   1 kevin  staff    34K Mar 20 08:23 ChangeLog
-rw-r--r--   1 kevin  staff   2.9K Mar 20 08:23 HACKING.md
-rw-r--r--   1 kevin  staff   8.2K Mar 20 08:23 INSTALL.md
-rw-r--r--   1 kevin  staff    26K Mar 20 08:23 LICENSE.md
-rw-r--r--   1 kevin  staff   3.8K Mar 20 08:23 Makefile.am
-rw-r--r--   1 kevin  staff   6.0K Mar 20 08:23 NEWS.md
-rw-r--r--   1 kevin  staff   6.1K Mar 20 08:23 README-windows.md
-rw-r--r--   1 kevin  staff   7.2K Mar 20 08:23 README.md
-rw-r--r--   1 kevin  staff   2.1K Mar 20 08:23 TODO.md
-rw-r--r--   1 kevin  staff   384K Mar 20 09:46 aclocal.m4
drwxr-xr-x  13 kevin  staff   442B Mar 20 08:23 android
drwxr-xr-x   7 kevin  staff   238B Mar 20 09:47 autom4te.cache
drwxr-xr-x  20 kevin  staff   680B Mar 20 09:47 config
-rw-r--r--   1 kevin  staff    92K Mar 20 09:59 config.log
-rwxr-xr-x   1 kevin  staff    87K Mar 20 09:59 config.status
-rwxr-xr-x   1 kevin  staff   877K Mar 20 09:46 configure
-rw-r--r--   1 kevin  staff    33K Mar 20 08:23 configure.ac
drwxr-xr-x   3 kevin  staff   102B Mar 20 08:23 dbus
drwxr-xr-x   8 kevin  staff   272B Mar 20 08:23 doc
drwxr-xr-x  27 kevin  staff   918B Mar 20 08:23 examples
drwxr-xr-x   6 kevin  staff   204B Mar 20 08:23 gtk
drwxr-xr-x   6 kevin  staff   204B Mar 20 09:46 include
drwxr-xr-x  24 kevin  staff   816B Mar 20 08:23 iphone
drwxr-xr-x   6 kevin  staff   204B Mar 20 08:23 java
-rw-r--r--   1 kevin  staff   316K Mar 20 09:46 ltmain.sh
drwxr-xr-x  15 kevin  staff   510B Mar 20 08:23 perl
drwxr-xr-x   4 kevin  staff   136B Mar 20 08:23 plugin
drwxr-xr-x  15 kevin  staff   510B Mar 20 09:46 po
drwxr-xr-x   5 kevin  staff   170B Mar 20 08:23 pygtk
drwxr-xr-x  20 kevin  staff   680B Mar 20 08:23 python
drwxr-xr-x   6 kevin  staff   204B Mar 20 08:23 qt
drwxr-xr-x  23 kevin  staff   782B Mar 20 08:23 test
drwxr-xr-x  43 kevin  staff   1.4K Mar 20 08:23 zbar
-rw-r--r--   1 kevin  staff   295B Mar 20 08:23 zbar-gtk.pc.in
-rw-r--r--   1 kevin  staff   295B Mar 20 08:23 zbar-qt.pc.in
-rw-r--r--   1 kevin  staff   297B Mar 20 08:23 zbar-qt5.pc.in
-rw-r--r--   1 kevin  staff   6.2K Mar 20 08:23 zbar.ico
-rw-r--r--   1 kevin  staff   9.7K Mar 20 08:23 zbar.nsi
-rw-r--r--   1 kevin  staff   239B Mar 20 08:23 zbar.pc.in
-rw-r--r--   1 kevin  staff   6.7K Mar 20 08:23 zbar.spec.in
drwxr-xr-x   8 kevin  staff   272B Mar 20 08:23 zbarcam
drwxr-xr-x   5 kevin  staff   170B Mar 20 08:23 zbarimg
```
I updated the git repository with the last 20 changes, and tried again. Same Issue.

**Comment by EchterAgo** [comment]
Hmmm, there is a `config.status` but not `Makefile`. Sounds like the configure process must have failed previously. Could you share the `config.log` file? Also, you could try resetting the submodule: `cd contrib/zbar && git reset --hard && git clean -dfx`

**Comment by Beakerboy** [comment]
Here is the config.log. I ran the git reset and it proceeded past the zbar section.
Now I see the following error:

> Collecting pycparser
> ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
>     pycparser from https://files.pythonhosted.org/packages/ae/e7/d9c3a176ca4b02024debf82342dab36efadfc5776f9c8db077e8f6e71821/pycparser-2.20-py2.py3-none-any.whl#sha256=7582ad22678f0fcd81102833f60ef8d0e57288b6b5fb00323d101be910e35705 (from cffi==1.14.5->-r ./contrib/deterministic-build/requirements.txt (line 1))
> 🗯  ERROR:  Could not install requirements

**Comment by Beakerboy** [comment]
It complies and runs! Thanks! Since the Badger wallet is now unsupported, and did not support NFTs, I was able to import my seed into Electron Cash SLP and see everything. Bitcoin.com wallet was unable to see any SLP transactions from Badger, and also does not support NFT. I should be able to consolidate everything now. The derivation path scanner is wicked awesome too! It turns out my seed has transactions on three different derivation paths.

So...on the To-Do list, it seems osx might have additional sha256 requirements for the requirements.txt file than other builds. I'm more than happy to pull request this. Should I make a separate requirements-osx.txt file, and have the build script cat that together with the existing requirements.txt?

**Comment by jcramer** [comment]
Excellent, glad you were able to get it working.  PR is more than welcome, we can share it with EC mainline project as well.

**Comment by Beakerboy** [comment]
Should I submit the PR against master, or is one of the other branches considered ‘dev’?

**Comment by jcramer** [comment]
master
