### ISSUE TITLE
CLI: addressconvert not showing SLP address

### ISSUE THREAD

**Issue by damascene** [simpleledger/Electron-Cash-SLP#201]
The `addressconvert` arguments shows cashaddress and legacy format when fed an address but it doesn't show SLP address.

example:
```
Electron-Cash-SLP-3.6.6  addressconvert bitcoincash:qqkg36nn0gnh2p7srvfu8de93y6gdp6hsur27htxng
{
    "cashaddr": "bitcoincash:qqkg36nn0gnh2p7srvfu8de93y6gdp6hsur27htxng",
    "legacy": "154UkX6Fi3hcZMYF2eXnDAvULKX7nJGEXC"
}
```
Please add the SLP  address format to the output. Currently if it was fed with an SLP address it will convert it but will not show it in the output as it does with cashaddress and legacy.

**Comment by jcramer** [comment]
A new command has been added to deal with this, `addressconvert_slp`.  To get it to work you'll need to follow the instructions provided from the cli to update your config file.
