### ISSUE TITLE
Restore BCH address to addrequest command

### ISSUE THREAD

**Issue by damascene** [simpleledger/Electron-Cash-SLP#212]
The command `addrequest` in Electron Cash SLP create a payment request with simple ledger address format but accepts BCH amount. I suggest returning the address format to bch and creating an `addrequest_slp` for slp.

Current addrequest doesn't support SLP request, it only replaces with slp address format.

```json
./electron-cash addrequest 0.5
{
    "URI": "simpleledger:qrthmpgy3dkccxy0qtrqu5cpt3krel58evpy9wdsj8?amount=0.5",
    "address": "qrthmpgy3dkccxy0qtrqu5cpt3krel58evpy9wdsj8",
    "amount": 50000000,
    "amount (BCH)": "0.5",
    "exp": null,
    "id": "79c1883b73",
    "memo": "",
    "status": "Unknown",
    "time": 1624089973
}
```

**Comment by OPReturnCode** [comment]
This was solved in #225. Closing the issue.
