### ISSUE TITLE
The token balance of FlexUSD is 0

### ISSUE THREAD

**Issue by theRealBitcoinClub** [simpleledger/Electron-Cash-SLP#222]
![balance0flexusdonelectroncash](https://user-images.githubusercontent.com/35400618/133462158-21bbb4c7-9b88-49b1-bee8-a6f388c0320b.png)
![txhistorytokens](https://user-images.githubusercontent.com/35400618/133462168-9e48c7d8-48c8-44cd-a03a-3813080a8dbf.png)

I am using the latest dev version of ElectronCashSLP

I had transferred flexUSD to this wallet about 4 weeks ago

I received the dividends of flexUSD and its listed correctly in the history

But the balance is 0

**Comment by theRealBitcoinClub** [comment]
i am using the graph server

**Comment by RowanSkie** [comment]
I suggest leaving it open for a day. Your SLP transactions haven't been validated at all.

**Comment by theRealBitcoinClub** [comment]
ty, how does this validation process work? any link you could share to learn about what is going on?

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by theRealBitcoinClub** [comment]
I opened a different wallet with lots of tokens and now i see that the verification takes a few hours.

But the other wallet mentioned above, with these flexUSD, has all the tx in the history marked with a date so they have been validated, or not?

**Comment by RowanSkie** [comment]
> I opened a different wallet with lots of tokens and now i see that the verification takes a few hours.
> 
> But the other wallet mentioned above, with these flexUSD, has all the tx in the history marked with a date so they have been validated, or not?

Not really. If there's a date but the icon isn't a checkmark, it means that the graph server hasn't fully validated them, and since you have tons of flexUSD transactions and the server data for flexUSD these days become as big as 300 MB, it naturally happens.

**Comment by theRealBitcoinClub** [comment]
Its resolved, the first checkmarks came in after restarting the app without any internet connection, then I restarted with internet connection and saw the graph downloads in the console. After a few minutes all had the green checkmark.

Maybe the issue was related to the fact that I was opening two wallets one after the other and when I open the 2nd wallet the verification is done for that one but not for the first anymore?

There might be a bug related to that.

I would also recommend to notify the user about the graph server downloads within the app status bar, not just the console.
