### ISSUE TITLE
Transaction No Verified

### ISSUE THREAD

**Issue by lucydjo** [simpleledger/Electron-Cash-SLP#228]
Hi !

All transactions in my wallet remain "Not Verified". 
However on the BCH explorer the transactions are confirmed. Do you know where the problem comes from?

https://i.ibb.co/m9qLC2D/Electron-Cash-SLP-Tqd-O4-B6p-Vn.png

Wallet version 3.6.6
Windows 10

Thx !

**Comment by damascene** [comment]
Hi, it just needs sometime to confirm and verify locally. A release with faster confirmation using SLPDB is in the build.

**Comment by OPReturnCode** [comment]
Please use the latest version.
