### ISSUE TITLE
Error message when paying BIP70 invoice

### ISSUE THREAD

**Issue by imaginaryusername** [simpleledger/Electron-Cash-SLP#25]
When paying a Bitpay BIP70 invoice from an SLP wallet, I encountered a "Errno 5: Input/Output Error" message. The invoice was still paid, but it would be good to get rid of the error message. As far as I can tell the error was not present in Electron-cash 3.3.1, using latest SLP master.

**Comment by cculianu** [comment]
I think this has since been fixed with James Cramer's merge of Electron Cash codebase into SLP.  Can you confirm this no longer happens so I can close it, if you have time? Thanks.. :)

**Comment by imaginaryusername** [comment]
It works now!

**Comment by cculianu** [comment]
Awesome.. thanks for the follow-up!
