### ISSUE TITLE
Linux: Crash when viewing token details

### ISSUE THREAD

**Issue by imaginaryusername** [simpleledger/Electron-Cash-SLP#35]
Command line output, not sure if useful: 

` KCrash: Application 'python3.7' crashing...`
` KCrash: Attempting to start /usr/libexec/drkonqi from kdeinit`

**Comment by imaginaryusername** [comment]
It happened again, I was able to obtain output from the Fedora crash reporter.

#6  0x00007f3dadfed9e9 in QWindow::destroy() () from /lib64/libQt5Gui.so.5
#7  0x00007f3dadfee5cf in QWindow::event(QEvent*) () from /lib64/libQt5Gui.so.5
#8  0x00007f3da6174d68 in ?? () from /lib64/libQt5Widgets.so.5
#9  0x00007f3da6118285 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /lib64/libQt5Widgets.so.5
#10 0x00007f3da611f9a0 in QApplication::notify(QObject*, QEvent*) () from /lib64/libQt5Widgets.so.5
#11 0x00007f3dac18c23e in ?? () from /usr/lib64/python3.7/site-packages/PyQt5/QtWidgets.so
#12 0x00007f3dadc41ec6 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /lib64/libQt5Core.so.5
#13 0x00007f3dadfdf60a in QGuiApplicationPrivate::processCloseEvent(QWindowSystemInterfacePrivate::CloseEvent*) () from /lib64/libQt5Gui.so.5
#14 0x00007f3dadfe4605 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /lib64/libQt5Gui.so.5
#15 0x00007f3dadfbf70b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib64/libQt5Gui.so.5
#16 0x00007f3d881ca85f in ?? () from /lib64/libQt5XcbQpa.so.5
#17 0x00007f3dadc40e0b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib64/libQt5Core.so.5
#18 0x00007f3dadc48ed6 in QCoreApplication::exec() () from /lib64/libQt5Core.so.5
#19 0x00007f3dac18ac7f in ?? () from /usr/lib64/python3.7/site-packages/PyQt5/QtWidgets.so
#20 0x00007f3dbec4fbd7 in _PyMethodDef_RawFastCallKeywords () from /lib64/libpython3.7m.so.1.0
#21 0x00007f3dbec4fe70 in _PyCFunction_FastCallKeywords () from /lib64/libpython3.7m.so.1.0
#22 0x00007f3dbecc5a60 in _PyEval_EvalFrameDefault () from /lib64/libpython3.7m.so.1.0
#23 0x00007f3dbec086f8 in _PyEval_EvalCodeWithName () from /lib64/libpython3.7m.so.1.0
#24 0x00007f3dbec4f5f1 in _PyFunction_FastCallKeywords () from /lib64/libpython3.7m.so.1.0
#25 0x00007f3dbecc533d in _PyEval_EvalFrameDefault () from /lib64/libpython3.7m.so.1.0
#26 0x00007f3dbec4f44a in _PyFunction_FastCallKeywords () from /lib64/libpython3.7m.so.1.0
#27 0x00007f3dbecc0791 in _PyEval_EvalFrameDefault () from /lib64/libpython3.7m.so.1.0
#28 0x00007f3dbec086f8 in _PyEval_EvalCodeWithName () from /lib64/libpython3.7m.so.1.0
#29 0x00007f3dbec095a3 in PyEval_EvalCodeEx () from /lib64/libpython3.7m.so.1.0
#30 0x00007f3dbec095cb in PyEval_EvalCode () from /lib64/libpython3.7m.so.1.0
#31 0x00007f3dbed31bc2 in ?? () from /lib64/libpython3.7m.so.1.0
#32 0x00007f3dbed338fa in PyRun_FileExFlags () from /lib64/libpython3.7m.so.1.0
#33 0x00007f3dbed34e58 in PyRun_SimpleFileExFlags () from /lib64/libpython3.7m.so.1.0
#34 0x00007f3dbed36f55 in ?? () from /lib64/libpython3.7m.so.1.0
#35 0x00007f3dbed372fc in _Py_UnixMain () from /lib64/libpython3.7m.so.1.0
#36 0x00007f3dbe7a6413 in __libc_start_main () from /lib64/libc.so.6
#37 0x000055f29cc1808e in _start ()
[Inferior 1 (process 25627) detached]

**Comment by cculianu** [comment]
Interesting stack trace. Someone broke Qt super hard on the C++ level.  Not easy to do!

Could either be a bug in Qt or .. really weird calls to python that trigger Qt to explode.

How does one reproduce this?

**Comment by imaginaryusername** [comment]
1. Start SLP
2. Go to "tokens", right click view token details
3. Muck around a bit on the token details window. I'm not sure if anything specific triggers it, or just a random time.

**Comment by cculianu** [comment]
I just managed to reproduce it on macOS as well, and it produces a similar stack trace. I'll look into it.

**Comment by cculianu** [comment]
@imaginaryusername Let me know if you can reproduce it after last commit.  I'm 95% sure it's solved now.  

Let me know so I can close issue...

**Comment by cculianu** [comment]
PS: For me the easiest way to reproduce was to keep opening and closing those windows until eventually it would blow up with a segfault.  Not sure if that's how to reproduce on Linux.. let me know if it's fixed for you regardless!

**Comment by imaginaryusername** [comment]
Tried, problem seemed to have disappeared. Will re-open if it crops up again.

**Comment by cculianu** [comment]
Awesome.  Phew!  Yeah it was a weird interaction between Python cleaning up an object at a time when Qt wasn't expecting it.  It's actually probably a bug in PyQt but this workaround seems to have solved it.

Thanks!
