### ISSUE TITLE
Error message when there is unconfirmed transaction in history, and a block comes in

### ISSUE THREAD

**Issue by imaginaryusername** [simpleledger/Electron-Cash-SLP#38]
Traceback (most recent call last):
  File "/home/user/bin/slp/electrum/gui/qt/main_window.py", line 800, in timer_actions
    self.slp_history_list.update_item_netupdate(*item)
  File "/home/user/bin/slp/electrum/gui/qt/slp_history_list.py", line 195, in update_item_netupdate
    items = self._allitems.get(itx_hash, [])
NameError: name 'itx_hash' is not defined

**Comment by cculianu** [comment]
Hey man thanks for reporting -- this was one bad commit like 3 commits ago.  It's since been fixed.  Can you pull latest git master? This shouldn't be happening.  That `itx_hash` reference no longer exists!

**Comment by imaginaryusername** [comment]
As far as I can see it's fixed.

**Comment by cculianu** [comment]
Awesome, thanks.  Yeah I introduce a bug inadvertently when I merged something from EC regular and didn't notice it for a good 6-10 hours.  You must have pulled during that time window and not pulled after -- hence your experiencing this bug.  I'm 100% sure it's gone.  Thanks for the follow-up.
