### ISSUE TITLE
Create token with name already exist

### ISSUE THREAD

**Issue by School47** [simpleledger/Electron-Cash-SLP#44]
If i try to create token with name alreasy exist, program show error message, but create transaction anyway.
https://explorer.bitcoin.com/bch/tx/7c405c3275ded9cf9c9fa3b854d69cab435548afa987ab9d196b885102e2fdfc
this transaction marked as valid, but i didn't get any tokens, cuz i chose name, already exist in another token (which i created in the past)

**Comment by jcramer** [comment]
This issue has been resolved in 9d1d4af
