### ISSUE TITLE
New token balance is 0

### ISSUE THREAD

**Issue by jcramer** [simpleledger/Electron-Cash-SLP#46]
Some users experience token balance = 0 (in Balance column of Tokens Tab) for several minutes after creating a new token.   One user reported that after restarting EC SLP the issue resolved itself.

@cculianu do you have time to try to create a few tokens and see if you experience this problem?  I'm not sure if we have something wonky going on in the GUI update trigger.

When I tried on MacOS i did not experience this problem.  @fyookball can you also try to create some tokens on Windows to see if you experience this issue?

**Comment by cculianu** [comment]
Yeah I think the culprit may be something in wallet.py not picking up the new tx.  It's not related to the GUI side -- you can CMD-R all you want, it still doesn't get seen.

I suspect `add_transaction` isn't being called to pick up the SLP parts, maybe?  Although it *should* be.

You may want to check out the `receive_history_callback` in wallet.py as a starting point (I'm just guessing here).

Or.. it could be something else. :/

**Comment by jcramer** [comment]
@cculianu I don't have this issue on MacOS, thoughts on why that is?

**Comment by cculianu** [comment]
Wow. Really. Now that's an enigma.  I'll try it again later tonight (see if it reproduces reliably).  Maybe it's super rare and I just "got lucky". :P

**Comment by jcramer** [comment]
@cculianu Nevermind, it is not a Windows bug.

This bug occurs only when creating new tokens on the first wallet file (after a EC fresh install, having not yet closed EC).  Creating a 2nd wallet file (never closing the first wallet file) does not have this same behavior.  

Here is what I did to come to reproduce this on MacOS:

1) Renamed `~/.electron-cash` to `~/.electron-cash-org` to simulate a fresh install
2) Create new wallet file `default_wallet` and funded with BCH
3) Create new token, the balance remains at 0.
4) Create a 2nd new token, the balance remains at 0.
5) Leaving `default_wallet` open, create a new wallet file `wallet_1`
6) Create a 3rd new token within `wallet_1`, balance correctly updates to `333333` as expected.

<img width="449" alt="image" src="https://user-images.githubusercontent.com/988195/54767601-dd084480-4bd3-11e9-8895-7612ba003d7a.png">

This behavior leaves me to wonder if something to do with how and when EC config file or wallet files are written to disk?  This is sort of a wild guess, but something strange is surely going on.

The bad part about this is that every new user will come across this bug, while "regular" users never see this bug.
