### ISSUE TITLE
Add a pre-broadcast SLP validity checker

### ISSUE THREAD

**Issue by jcramer** [simpleledger/Electron-Cash-SLP#50]
In order to prevent token burns in the case of wallet bugs a validity check should be made on transactions before they are broadcasted to the network.  Ideally, the checker will take raw transaction buffer and parse it for SLP metadata and validate.

**Comment by jcramer** [comment]
Hey @markblundeberg, this was originally your idea so if you have some spare time please take a look at `SlpWallet.check_tx_slp()` added in 48fc65b.  

Basically this method is added just before any call to broadcast_transaction().  

Two issues I have:
- When this method throws an exception main_window displays a error message window, but there isn't any text in the error message.  Do I need to include some text as part of the custom exceptions?
- I tested this pretty well, but I still would like to add some unit tests around it.  Shouldn't be too difficult will just take some more time.

I want to move some of the other wallet.py methods that are specific to SLP to this method as static methods (with wallet passed in as param).  Curious of your thoughts on this approach for organizing the SLP parts specific requiring interaction with the wallet object.

**Comment by markblundeberg** [comment]
Hmm I don't remember having this idea but it looks OK. Ideally this sort of thing should not be needed, though -- the code should be doing the right thing in the first place. :-)

One thing that's not clear to me is how this fits into the picture of how token system will work if this is ever merged into Electron Cash. I'm not sure what that result looks like, so I can't say whether this helps us towards that goal or not.

**Comment by jcramer** [comment]
IIRC didn't we discuss the concept of adding a final checker that looks for spending outputs that may be associated with OP_RETURN protocols?  I guess I just wanted to make sure we at least have this for SLP.  Bugs happen and if we have a last line of defense from allowing someone's ACD, USDH, LLM, or BTC2 from being burned it makes me feel better.

I think it's important to have this type of final check pre-sign or pre-broadcast even after the merge with mainline.  I'm not seeing the problem with how this new code would have any negative impact on mainline.  I guess the only thing is just more intrusive integration of SLP into the whole code base (which @cculianu won't like) under the goal preventing token burns.

Maybe it would make more sense to have the check pre-sign? Why sign something that's wrong? User could just copy signed transaction and broadcast elsewhere.

**Comment by jcramer** [comment]
Closing this now, as this https://github.com/simpleledger/Electron-Cash-SLP/commit/48fc65bdc6652aee098fd25a19b3711b3207f644#r34093984 should be addressed in the above commit.
