### ISSUE TITLE
SLP Use of QTreeWidgetItem

### ISSUE THREAD

**Issue by cculianu** [simpleledger/Electron-Cash-SLP#53]
We got this crash report:

https://github.com/Electron-Cash/Electron-Cash/issues/1261

I wrote about this in the channel on telegram before realizing the issue tracker is perhaps a more appropriate place:

This happens with context menus (right click menus) that keep references to QTreeWidgetItems (in their lambdas).

QTreeWidgetItems are ephemeral because every "update()" call they get cleared (deleted in C++) and so keeping references to them leads to this exception in the crash report linked above.

What happens is this:

1. User right-clicks something in the tokens tab or wherever
2. Code generates a menu "on the fly" with each item in the menu calling a closure (lambda)
3. While the menu is up, an update occurs and the content of the tab is refreshed (it may end up being the same content)
4. Refreshing destroys everything and rebuilds it -- including the QTreeWidgetItems
5. Now user clicks on a menu action and the lambda or function call it triggers has a reference to a now defunct QTreeWidgetItem than was cleared in the intervening time.

So -- the solution is: You gotta keep a reference instead to something you can use to "look them up on the fly" when creating the menu callback lambdas -- such as a token ID or whatever.  So when the user picks an action -- the lambda or callback doesn't hold a reference to the QTreeWidgetItem they right-clicked on (which may get deleted at any time) -- but instead you have to "look it up" on the fly based on something unchanging like a tokenID or whatever.

You can see the coins tab or other stuff from EC mainline about how it handles the situation with context menus and not keeping refs to 'item' (QTreeWidgetItem)

**Comment by cculianu** [comment]
I wanted to create this issue to alert you to this PyQt gotcha -- I can easily fix this for you.  But wanted you to be aware of it since it's the type of annoying bug that only causes problems intermittently so it can easily go unnoticed.... and I wanted to take this opportunity to alert you to its existence so new code you write doesn't do this.

(You did inherit some questionable code from EC as did I .. :P )

**Comment by jcramer** [comment]
@cculianu does this address the issue? I was able to reproduce the error on the "View Token Details" button, and it looks fixed now.

Interesting that "Copy Token ID" and "Remove this token" buttons do not suffer from this same issue, at least I didn't get a similar error with those buttons.

**Comment by cculianu** [comment]
You did indeed fix it -- that was the problem.

I wouldn't create 2 new member variables (attributes as Python calls them) for it though if I could avoid it.  It's sufficient just to query for `self.currentItem()` again. See my comments.

**Comment by cculianu** [comment]
@jcramer Oops.. forgot to tag u. Not sure if you get it or not. heh ^^

**Comment by jcramer** [comment]
> @jcramer Oops.. forgot to tag u. Not sure if you get it or not if I don't tag. heh ^^

I do still get the email message :)

**Comment by jcramer** [comment]
> You did indeed fix it -- that was the problem.
> 
> I wouldn't create 2 new member variables (attributes as Python calls them) for it though if I could avoid it. It's sufficient just to query for `self.currentItem()` again. See my comments.

See updated patch.

**Comment by cculianu** [comment]
Ha looks good! Sorry to be  a nazi -- it's just eventually you know.. murphy's law.  And every exception crash report makes me die a little bit inside.. so :)

Cool. Looks good. thanks.
