### ISSUE TITLE
Display minting baton

### ISSUE THREAD

**Issue by CipherGnome** [simpleledger/Electron-Cash-SLP#55]
Electron cash should show when there is a minting baton in the wallet.

When creating a new token if the minting baton is sent to an electron cash SLP wallet it is currently not shown anywhere. This makes it difficult to track the UTXO of the baton.

**Comment by jcramer** [comment]
Excellent idea, I will try to add something to the Coins tab for this soon.

I also want to add to the coins tab an indication of the token being held by each UTXO

**Comment by jcramer** [comment]
I'm going to close this because the baton is now displayed in the Tokens tab.  Spending the baton is accomplished by right-clicking on the token and using "Mint tool".
