### ISSUE TITLE
Minting is broken in 3.4.7

### ISSUE THREAD

**Issue by jcramer** [simpleledger/Electron-Cash-SLP#59]
Token minting batons are safe in 3.4.7,  but the wallet will not mint additional tokens due to a change in the method `get_utxos` being called here:

https://github.com/simpleledger/Electron-Cash-SLP/blob/ff1bff29a1aab41bf1039734ac2f3f7cec611994/lib/wallet.py#L721

The method should be changed to `get_slp_utxos`.

**Comment by cculianu** [comment]
Wow man that's pretty serious.  I guess you need to do another release ASAP?  Who broke it? I hope it wasn't me during a merge.. I don't recall touching that.

Good luck man.

**Comment by jcramer** [comment]
> Wow man that's pretty serious. I guess you need to do another release ASAP? Who broke it? I hope it wasn't me during a merge.. I don't recall touching that.
> 
> Good luck man.

I broke it, and its fixed now.  It just doesn't allow access to Mint GUI. 

Protection of the mint baton is not impacted.
