### ISSUE TITLE
Disable OP_RETURN in GUI when sending tokens

### ISSUE THREAD

**Issue by imaginaryusername** [simpleledger/Electron-Cash-SLP#70]
Right now it seems like Electron-Cash SLP does not support sending op_return at all, but the blank is still there if you enable in preferences in Electron-cash regular (entering things do nothing to the final transaction, so it's at least token safe) - which can be confusing. 

Recommended behavior to ease merging: 

1. Enable the OP_RETURN box in preferences instead of greying it out. 

2. If sending "None", the field behaves normally (follows preferences) as in Electron-Cash mainline.

3. If sending tokens, the field is properly greyed out even if enabled in preferences, and op_return is dedicated to tokens instead.

**Comment by jcramer** [comment]
please let me know this meets your requirements :)
