### ISSUE TITLE
Issue with address list index with "imported_priv_key" wallet type

### ISSUE THREAD

**Issue by jcramer** [simpleledger/Electron-Cash-SLP#85]
This might be EC mainline issue also, not sure yet.

<img width="398" alt="image" src="https://user-images.githubusercontent.com/988195/63612159-90be9780-c5ab-11e9-828b-11d034b62c32.png">

**Comment by cculianu** [comment]
Probably wallet.py `delete_address` or whatever functions handle totally removing an address and its history needs to take into account the tokens too.

**Comment by jcramer** [comment]
Closing this as I was not able to replicate this edge case.  Also, it appears in the above screenshot that the error was caught with a warning message displayed to the user.
