### ISSUE TITLE
New address not generated after transactions in SLP wallet

### ISSUE THREAD

**Issue by jcramer** [simpleledger/Electron-Cash-SLP#91]
~~After using the token Genesis and Mint forms to create new tokens, the address displayed in the Receive tab is not updated to the next unused address.~~

EDIT: It turns out this was being caused by using an older SLP wallet that already had "use_change"  set to False.  Since we only want SLP wallets to have "use_change" to be True we needed to enforce this on older SLP wallets who already set "use_change" to False.

**Comment by jcramer** [comment]
@cculianu please ACK

**Comment by cculianu** [comment]
Hi.. what’s up?

**Comment by cculianu** [comment]
Ok.. I’ll review it a little later. Not at home at the moment.
