### ISSUE TITLE
Can't Import non-SLP 12 Word Seed into SLP EC

### ISSUE THREAD

**Issue by cryptoshoppe** [simpleledger/Electron-Cash-SLP#96]
![electron-cash-cant-import](https://user-images.githubusercontent.com/48914148/65821897-d9e8b380-e209-11e9-8128-4e534e811310.png)

Not sure if this is a big issue, but wanted to point this out.

**Comment by jcramer** [comment]
From our discussion in the chat, I saw in the chat that you resolved this issue.
